- name: install catalogue component
  hosts: catalogue.nagasweb.online
  become: yes
  tasks:

  - name: setup NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"