- name: install mongodb
  hosts: mongodb
  become: yes
  tasks:
  
  - name: Setup the MongoDB repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install MongoDB
    ansible.builtin.yum:
      name: mongodb-org
      status: installed